language: php
php:
  - '8.0'
services:
  - mysql
only:
  - main
  - develop
  - pre-prod
cache:
  directories:
    - node_modules
    - vendor
jobs:
  include:
    - stage: build
      before_script:
        - cp .env.travis .env
        - sudo mysql -e 'create database testing;'
        - composer self-update
      script:
        - composer install --prefer-source --no-interaction --dev
        - npm install
        - php bin/console doctrine:migrations:migrate
        - composer dump-autoload
    - stage: after
      after_success:
        - composer dump-autoload
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      after_failure:
        - composer dump-autoload
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL