<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC1v5wgO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC1v5wgO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC1v5wgO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC1v5wgO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC1v5wgO\App_KernelDevDebugContainer([
    'container.build_hash' => 'C1v5wgO',
    'container.build_id' => '8248a3ef',
    'container.build_time' => 1638777586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC1v5wgO');
